services:
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_DATABASE: 'myschoolDB'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 160

  app:
    build: .
    command: >
      sh -c './create_superuser_prod.sh'
    restart: always
    ports:
      - "8080:8080"
    environment:
      HOST: "db"
      PORT: 3306
      NAME: "myschoolDB"
      PASSWORD: "root"
      USER: "root"
      DJANGO_SUPERUSER_NAME: "admin"
      DJANGO_SUPERUSER_EMAIL: "admin@email.com"
      DJANGO_SUPERUSER_PASSWORD: "admin"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-volume:
