# Generated by Django 5.1 on 2024-08-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birthdate', models.DateField()),
                ('course', models.ManyToManyField(to='mySchoolApp.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
